separador=("-_-"*30)
print("***************INFORMACION**************")
print("****balance general****")
print(separador)
print("activos ")
print(separador)
efec=(int(input("efectivos: ")))
cli=(int(input("clientes: ")))
deudo=(int(input("deudores diversos: ")))
fun=(int(input("funcionarios y empleados: ")))
int_mst=(int(input("inventario de materiales: ")))
int_tert=(int(input("inventario de producto terminado: $")))
totl_act=(efec + cli + deudo + fun + int_mst + int_tert)
print("total de activo circulante: ", totl_act)
print(separador)
terr=(int(input("terreno: ")))
plant=(int(input("planta y equipo: ")))
decer=(int(input("depreciacion acomulada: ")))
total_no=(terr + plant - decer)
print("total de activo no circulante: ", total_no)
print(separador)
act_tot=(totl_act + total_no)
print("activo total: ", act_tot)
print(separador)
print("pasivos ")
print(separador)
provee=(int(input("proveedores: ")))
docum=(int(input("documentos por pagar: ")))
isr=(int(input("ISR por pagar: ")))
total_corto=(provee + docum + isr)
print("total de pasivo corto plazo: ", total_corto)
print(separador)
presr=(int(input("prestamos bancarios: ")))
total_largo=(presr)
print("total de pasivos largo plazo: ", total_largo)
pasivo_total=(total_corto + total_largo)
print("pasivo total: ", pasivo_total)
print(separador)
print("capital contable")
print(separador)
capo=(int(input("capital contribuido: ")))
cap_gan=(int(input("capital ganado")))
total_capital_contable=(capo + cap_gan)
print("capital contable total: ", total_capital_contable)
suna_pasivo_capital=(pasivo_total + total_capital_contable)
print("suma del pasivo y capital: ",suna_pasivo_capital)
###################################################################################################
print("requerimientos de materiales")
print("proyecto uno")
materia_prima_1=(int(input("materia prima a (metros): ")))
materia_prima_2=(int(input("materia prima b (metros): ")))
materia_prima_3=(int(input("materia prima c (piezas): ")))
horas_mano_de_obra=(int(input("horas de mano de obra: ")))
print(materia_prima_1 , materia_prima_2 , materia_prima_3 , horas_mano_de_obra)
print(separador)
print("proyecto dos")
materia_prima_10=(int(input("materia prima a (metros): ")))
materia_prima_20=(int(input("materia prima b (metros): ")))
materia_prima_30=(int(input("materia prima c (piezas): ")))
horas_mano_de_obra0=(int(input("horas de mano de obra: ")))
print(materia_prima_10 , materia_prima_20 , materia_prima_30 , horas_mano_de_obra0)
print(separador)
print("proyecto tres")
materia_prima_11=(int(input("materia prima a (metros): ")))
materia_prima_21=(int(input("materia prima b (metros): ")))
materia_prima_31=(int(input("materia prima c (piezas): ")))
horas_mano_de_obra1=(int(input("horas de mano de obra: ")))
print(materia_prima_11 , materia_prima_21 , materia_prima_31 , horas_mano_de_obra1)
print(separador)
###################################################################################################
print("informacion de inventarios")
print(separador)
print("inventario inicial primer semestre")
mate=(int(input("materia prima a (metro): ")))
matea=(int(input("materia prima b (metro): ")))
mates=(int(input("materia prima c (piezas): ")))
proc=(int(input("producto 1: ")))
procc=(int(input("producto 2: ")))
proccc=(int(input("producto 3: ")))
print(separador)
print("inventario final segundo semestre")
mate1=(int(input("materia prima a (metro): ")))
matea1=(int(input("materia prima b (metro): ")))
mates1=(int(input("materia prima c (piezas): ")))
proc1=(int(input("producto 1: ")))
procc1=(int(input("producto 2: ")))
proccc1=(int(input("producto 3: ")))
print(separador)
print("costo primer semestre")
mate12=(int(input("materia prima a (metro) : $")))
matea12=(int(input("materia prima b (metro) : $")))
mates12=(int(input("materia prima c (piezas) : $")))
print(separador)
print("costo segundo semestre")
mate10=(int(input("materia prima a (metro) : $")))
matea10=(int(input("materia prima b (metro) : $")))
mates10=(int(input("materia prima c (piezas) : $")))
###################################################################################################
print(separador)
print("productos")
print(separador)
print("proyecto 1")
vend=(int(input("precio de ventas primer semestre: $")))
segr=(int(input("precio de venta segundo semestre: $")))
planet=(int(input("ventas planeadas primer semestre: ")))
planita=(int(input("ventas planeadas segundo semestre: ")))
print(separador)
print("proyecto 2")
vend1=(int(input("precio de ventas primer semestre: $")))
segr1=(int(input("precio de venta segundo semestre: $")))
planet1=(int(input("ventas planeadas primer semestre: ")))
planita1=(int(input("ventas planeadas segundo semestre: ")))
print(separador)
print("proyecto 3")
vend2=(int(input("precio de ventas primer semestre: $")))
segr2=(int(input("precio de venta segundo semestre: $")))
planet2=(int(input("ventas planeadas primer semestre: ")))
planita2=(int(input("ventas planeadas segundo semestre: ")))
print(separador)
###################################################################################################
print("gastos de administracion y ventas:")
depre=(int(input("depreciacion (anuales): ")))
ss=(int(input("sueldos y salarios (anuales): ")))
cum=(int(input("comisiones (porcentaje de las ventas): ")))
vari=(int(input("varios (primer semestre): ")))
varen=(int(input("varios (segundo semestre): ")))
inteli=(int(input("interes por prestamo (anuales): ")))
print(separador)
###################################################################################################
print("gastos de fabricacion indirectos")
depress=(int(input("depreciacion (anuales): ")))
segutos=(int(input("seguros (anuales): ")))
manteni=(int(input("mantenimiento (primer semestre): ")))
manteri=(int(input("mantenimiento (segundo semestre): ")))
ener=(int(input("energeticos (primer semestre): ")))
enery=(int(input("energeticos (segundo semestre): ")))
vanito=(int(input("varios (anuales): ")))
print(separador)
########   MEJORAR ##############################################
                            #
                            #
                            #
                            #
                            #
                            #
                        #   #   #
                            #


###################################################################################################
print("***********PRESUPUESTO MAESTRO**************")
print(separador)
print("1-.presupuesto de ventas")
print(separador)
print("producto 1")
print("*primer semestre*")
print("Unidades a vender: " , planet)
print("Precio de ventas: ", vend)
impot=(planet * vend)
print("importe de venta: ", impot)
print(separador)
print("*segundo semestre*")
print("Unidades a vender: ",planita)
print("Precio de ventas: ", segr)
impot1=(planita * segr)
print("importe de venta: ", impot1)
print(separador)
sum1=(impot + impot1)
print("producto 2")
print("*primer semestre*")
print("Unidades a vender: " , planet1)
print("Precio de ventas: ", vend1)
impot2=(planet1 * vend1)
print("importe de venta: ", impot2)
print(separador)
print("*segundo semestre*")
print("Unidades a vender: ",planita1)
print("Precio de ventas: ", segr1)
impot3=(planita1 * segr1)
print("importe de venta: ", impot3)
sum2=(impot2 + impot3)
print(separador)
print("producto 3")
print("*primer semestre*")
print("Unidades a vender: " , planet2)
print("Precio de ventas: ", vend2)
impot4=(planet2 * vend2)
print("importe de venta: ", impot4)
print(separador)
print("*segundo semestre*")
print("Unidades a vender: ",planita2)
print("Precio de ventas: ", segr2)
impot5=(planita2 * segr2)
print("importe de venta: ", impot5)
sum3=(impot4 + impot5)
print(separador)
print("total de venta por semestre")
prim_re=(impot + impot2 + impot4  )
seg_tre=(impot1 + impot3 + impot5)
print("primer semestre: ", prim_re)
print("segundo semestre: ", seg_tre)
print(separador)
sum4=(sum1 + sum2 + sum3)
print("total de venta por año")
print("producto 1: ", sum1)
print("producto 2: ", sum2)
print("producto 3: ", sum3)
print("total: ", sum4 )
porce=(sum4 * 0.20)
print(separador)
###################################################################################################
print("2-.presupuesto de determinacion de saldo de clientes y flujo de entradas")
print("saldo de clientes: ", cli)
print("ventas totales del año: ", sum4)
total_clim=(cli + sum4)
print("total de clientes: ", total_clim)
print(separador)
print("entrada de efectivo: ")
print("cobranza del primer año: ", cli)
uwu=(sum4 * 0.8)
print("cobranza del presente año: ", uwu)
sint=(cli + uwu)
print(sint)
tern8m=(total_clim - sint)
print("saldo de clientes del presente año: ", tern8m)
print(separador)
###################################################################################################
print("3-.presupuesto de produccion")
print("proyecto 1")
print("primer semestre")
print("unidades de vender: ", planet)
print("(+) inventario final: ", proc)
zuma=(planet + proc)
print("(=) total de unidades: ", zuma)
print("(-)inventario inicial: ", proc)
restav=(zuma - proc)
print("(=)unidades a producir: " , restav)
print(separador)
print("segudo semestre")
print("unidades de vender: ", planita)
print("(+) inventario final: ", proc1)
zuma1=(planita + proc1)
print("(=) total de unidades: ", zuma1)
print("(-)inventario inicial: ", proc)
restav1=(zuma1 - proc)
print("(=)unidades a producir: " , restav1)
print(separador)
print("totales")
loc=(planet + planita)
loki=(zuma + zuma1)
lokin=(restav + restav1)
print("unidades a vender: ", loc)
print("inventario final: " , proc1)
print("total de unidades: ", loki)
print("inventario inicial:", proc)
print("unidades de producir: ", lokin)
print(separador)
print("proyecto 2")
print("primer semestre")
print("unidades de vender: ", planet1)
print("(+) inventario final: ", procc)
zumac=(planet1 + procc)
print("(=) total de unidades: ", zumac)
print("(-)inventario inicial: ", procc)
restave=(zumac - procc)
print("(=)unidades a producir: " , restave)
print(separador)
print("segudo semestre")
print("unidades de vender: ", planita1)
print("(+) inventario final: ", procc1)
zuma11=(planita1 + procc1)
print("(=) total de unidades: ", zuma11)
print("(-)inventario inicial: ", procc1)
restav11=(zuma11 - procc1)
print("(=)unidades a producir: " , restav11)
print(separador)
print("totales")
loc1=(planet1 + planita1)
loki1=(zumac + zuma11)
lokin1=(restave + restav11)
print("unidades a vender: ", loc1)
print("inventario final: " , procc1)
print("total de unidades: ", loki1)
print("inventario inicial:", procc)
print("unidades de producir: ", lokin1)
print(separador)
print("proyecto 3")
print("primer semestre")
print("unidades de vender: ", planet2)
print("(+) inventario final: ", proccc)
zumaco=(planet2 + proccc)
print("(=) total de unidades: ", zumaco)
print("(-)inventario inicial: ", proccc)
restavel=(zumaco - proccc)
print("(=)unidades a producir: " , restavel)
print(separador)
print("segudo semestre")
print("unidades de vender: ", planita2)
print("(+) inventario final: ", proccc1)
zuma111=(planita2 + proccc1)
print("(=) total de unidades: ", zuma111)
print("(-)inventario inicial: ", proccc1)
restav111=(zuma111 - proccc1)
print("(=)unidades a producir: " , restav111)
print(separador)
print("totales")
loc10=(planet2 + planita2)
loki10=(zumaco + zuma111)
lokin10=(restavel + restav111)
print("unidades a vender: ", loc10)
print("inventario final: " , procc1)
print("total de unidades: ", loki10)
print("inventario inicial:", procc)
print("unidades de producir: ", lokin10)
print(separador)
###################################################################################################
print("4-.presupuesto de requerimiento de materiales")
print(separador)
print("producto 1")
print("unidades a producir primer semestre: " , restav)
print("unidades a producir segundo semestre: ", restav1)
print(separador)
print("producto 2")
print("unidades a producir primer semestre: ", restave)
print("unidades a producir segundo semestre: ", restav11)
print(separador)
print("producto 3")
print("unidades a producir primer semestre: ", restavel)
print("unidades a producir segundo semestre: ", restav111)
print(separador)
print("totales de año")
print("unidades de producir (p1): ", lokin)
print("unidades de producir (p2): ", lokin1)
print("unidades de producir (p3): ", lokin10 )
###################################################################################################
print("proyecto 1")
print("primer semestre")

print("material a")
print("requerimiento de material: ", materia_prima_1)
m1=(restav * materia_prima_1)
print("total de material a requerido:" , m1)

print("material b")
print("requerimiento de material: ", materia_prima_2)
m2=(restav * materia_prima_2)
print("total de material b requerido:", m2)

print("material c")
print("requerimiento de material: ", materia_prima_3)
m3=(restav * materia_prima_3)
print("total de material c requerido:", m3)
print(separador)


print("proyecto 2")
print("material a")
print("requerimiento de material: ", materia_prima_10)
m10=(restave * materia_prima_10)
print("total de material a requerido:", m10)
print("material b")
print("requerimiento de material: ", materia_prima_20)
m20=(restave * materia_prima_20)
print("total de material b requerido:", m20)
print(separador)
print("material c")
print("requerimiento de material: ", materia_prima_30)
m30=(restave * materia_prima_30)
print("total de material c requerido:", m30)
print(separador)
print("proyecto 3")
print("material a")
print("requerimiento de material: ", materia_prima_11)
m11=(restavel * materia_prima_11)
print("total de material a requerido:", m11)
print(separador)
print("material b")
print("requerimiento de material: ", materia_prima_21)
m21=(restavel * materia_prima_21)
print("total de material b requerido:", m21)
print(separador)
print("material c")
print("requerimiento de material: ", materia_prima_31)
m31=(restavel * materia_prima_31)
print("total de material c requerido:", m31)
print(separador)
########################################################################################
print("segundo semestre")
print("proyecto 1")
print("material a")
print("requerimiento de material: ", materia_prima_1)
m100=(restav1 * materia_prima_1)
print("total de material a requerido:" , m100)
print(separador)
print("material b")
print("requerimiento de material: ", materia_prima_2)
m200=(restav1 * materia_prima_2)
print("total de material b requerido:", m200)
print(separador)
print("material c")
print("requerimiento de material: ", materia_prima_3)
m300=(restav1 * materia_prima_3)
print("total de material c requerido:", m300)
print(separador)
print("proyecto 2")
print("material a")
print("requerimiento de material: ", materia_prima_10)
m101=(restav11 * materia_prima_10)
print("total de material a requerido:", m101)
print("material b")
print("requerimiento de material: ", materia_prima_20)
m202=(restav11 * materia_prima_20)
print("total de material b requerido:", m202)
print(separador)
print("material c")
print("requerimiento de material: ", materia_prima_30)
m303=(restav11 * materia_prima_30)
print("total de material c requerido:", m303)
print(separador)
print("proyecto 3")
print("material a")
print("requerimiento de material: ", materia_prima_11)
m111=(restav111 * materia_prima_11)
print("total de material a requerido:", m111)
print(separador)
print("material b")
print("requerimiento de material: ", materia_prima_21)
m212=(restav111 * materia_prima_21)
print("total de material b requerido:", m212)
print(separador)
print("material c")
print("requerimiento de material: ", materia_prima_31)
m312=(restav111 * materia_prima_31)
print("total de material c requerido:", m312)
print(separador)
#############################################################################
print("totales")
print("proyecto 1")
print("Material a")
print("requerimiento de material: ", materia_prima_1)
zx=(m1 + m100)
print("total de material requerido: ", zx)
print(separador)
print("Material b")
print("requerimiento de material: ", materia_prima_2)
zx0=(m2 + m200)
print("total de material requerido: ", zx0)
print(separador)
print("Material c")
print("requerimiento de material: ", materia_prima_3)
zx1=(m3 + m300)
print("total de material requerido: ", zx1)
print(separador)
print("proyecto 2")
print("Material a")
print("requerimiento de material: ", materia_prima_10)
cv=(m10 + m101)
print("total de material requerido: ", cv)
print(separador)
print("Material b")
print("requerimiento de material: ", materia_prima_20)
cv1=(m20 + m202)
print("total de material requerido: ", cv1)
print(separador)
print("Material c")
print("requerimiento de material: ", materia_prima_30)
cv2=(m30 + m303)
print("total de material requerido: ", cv2)
print(separador)
print("proyecto 3")
print("Material a")
print("requerimiento de material: ", materia_prima_11)
nm=(m11 + m111)
print("total de material requerido: ", nm)
print(separador)
print("Material b")
print("requerimiento de material: ", materia_prima_21)
mn=(m21 + m212)
print("total de material requerido: ", mn)
print(separador)
print("Material c")
print("requerimiento de material: ", materia_prima_31)
mnb=(m31 + m312)
print("total de material requerido: ", mnb)
print(separador)
#############################################################
print("total de requerimientos (gramos)")
print("primer semestre")
lo=(m1 + m10 + m11)
ol=(m2 + m20 + m21)
lop=(m3 + m30 + m31)
print("material a: ", lo)
print("material b: ", ol)
print("material c: ", lop)
print(separador)
print("segundo semestre")
lo1=(m100 + m101 + m111)
ol1=(m200 + m202 + m212)
lop1=(m300 + m303 + m312)
print("material a: ", lo1)
print("material b: ", ol1)
print("material c: ", lop1)
print(separador)
print("año")
gh=(lo + lo1)
hj=(ol + ol1)
jk=(lop + lop1)
print("material a: ", gh)
print("material b: ", hj)
print("material c: ", jk)
print(separador)
#########################################################################
print("5-.presupuesto de compra de materiales")
print("primer semestre")
print("material a")
print(separador)
print("requerimiento de materiales: ", lo)
print("(+)inventario final: ", mate)
total_de=(lo + mate)
print("total de materiales: ", total_de)
print("(-)inventario inicial: ", mate)
df=(total_de - mate)
print("material a comprar (metros): ", df)
print("precio de compra: $", mate12)
vcx=(df * mate12)
print("total de material A en $: $", vcx)
print(separador)

print("material b")
print("requerimento de materiales:",ol)
print("(+)inventario inicial: ", matea)
total_de_0=(ol + matea)
print("total de materiales: ", total_de_0)
print("(-)inventario inicial: ", matea)
df1=(total_de_0 - matea)
print("material a comprar (metros): $", df1)
print("precio de compra: $", matea12)
vcxz=(df1 * matea12)
print("total de material B en $: $", vcxz)
print(separador)

print("material c")
print("requerimiento de materiales:", lop)
print("(+)inventario final:", mates)
total_de_1=(lop + mates)
print("total de materiales: ", total_de_1)
print("(-)inventario inicial: ",mates)
df2=(total_de_1 - mates)
print("material a comprar (metros): ", df2)
print("precio de compra: $", mates12)
vcxzb=(df2 * mates12)
print("total de material C en $: $", vcxzb)
print(separador)

print("segundo semestre")
print("material a")
print(separador)
print("requerimiento de materiales: ", lo1)
print("(+)inventario final: ", mate1)
total_deu=(lo1 + mate1)
print("total de materiales: ", total_deu)
print("(-)inventario inicial: ", mate1)
df5=(total_deu - mate1)
print("material a comprar (metros): ", df5)
print("precio de compra: $", mate10)
vcx651=(df5 * mate10)
print("total de material A en $: $", vcx651)
print(separador)

print("material b")
print("requerimento de materiales:",ol1)
print("(+)inventario inicial: ", matea1)
total_de_05=(ol1 + matea1)
print("total de materiales: ", total_de_05)
print("(-)inventario inicial: ", matea1)
df11=(total_de_05 - matea1)
print("material a comprar (metros): $", df11)
print("precio de compra: $", matea10)
vcxz8=(df11 * matea10)
print("total de material B en $: $", vcxz8)
print(separador)

print("material c")
print("requerimiento de materiales:", lop1)
print("(+)inventario final:", mates1)
total_de_14=(lop1 + mates1)
print("total de materiales: ", total_de_14)
print("(-)inventario inicial: ",mates1)
df20=(total_de_14 - mates1)
print("material a comprar (metros): ", df20)
print("precio de compra: $", mates10)
vcxzbw=(df20 * mates10)
print("total de material C en $: $", vcxzbw)
print(separador)

print("totales del año")
print("material A")
print("requerimiento de materiales: ", gh)
print("inventario final: ", mate1)
zo=(total_de + total_deu)
print("total de materiales: ", zo)
print("inventario inicial: " , mate)
de=(df - df5)
print("material a comprar: ", de)
mj=(vcx + vcx651)
print("total de material A en $: $", mj)
print(separador)
print(separador)
print("material B")
print("requerimiento de materiales: ", hj)
print("inventario final: ", matea1)
zo2=(total_de_0 + total_de_05)
print("total de materiales: ", zo2)
print("inventario inicial: " , matea)
de1=(df1 - df11)
print("material a comprar: ", de1)
mj1=(vcxz + vcxz8)
print("total de material B en $: $", mj1)
print(separador)
print("material C")
print("requerimiento de materiales: ", jk)
print("inventario final: ", mates1)
zo3=(total_de + total_deu)
print("total de materiales: ", zo3)
print("inventario inicial: " , mates)
de2=(df2 - df20)
print("material a comprar: ", de2)
mj2=(vcxzb + vcxzbw)
print("total de material C en $: $", mj2)
print(separador)
print("compras totales")
opi=(vcx + vcxz + vcxzb)
print("primer semestre: ", opi)
yui=(vcx651 + vcxz8 + vcxzbw)
print("segundo semestre: ", yui)
rty=(zo + zo2 + zo3)
print("año: ", rty)
print(separador)

decsf=(rty / 0.50)

print("6-.detrminacion del saldo de proveedores y flujo de salidas")
print("saldo de proveedores: ", provee)
print("compras: ", rty)
hjg=(provee + rty)
print("total de proveedores", hjg)
print("salidas de efectivo")
print("por proveedores del año pasado: ", provee)
bbb=(rty * 0.5)
print("proveedores del año actual: ", bbb)
ggg=(provee + bbb)
print("total de salidas: ", ggg)
ttt=(hjg - ggg)
print("saldo de proveedores: ", ttt)

print(separador)

print("7-. presupuesto de mano de obra directa")
print("primer semestre")
print("producto A")
print("unidades a producir: ", restav)
print("horas requeridas por unidad: ", horas_mano_de_obra)
nnn=(restav * horas_mano_de_obra)
print("horas de horas requeridas" , nnn)
cua_0=(int(input("cuota por hora")))
mmm=(nnn * cua_0)
print("Importe de M.O.D", mmm)
print(separador)

print("producto B")
print("unidades a producir: ", restave)
print("horas requeridas por unidad: ", horas_mano_de_obra0)
nnn1=(restave * horas_mano_de_obra0)
print("total de horas requeridas", nnn1)
cua_=(int(input("cuota por hora")))
mmm1=(nnn1 * cua_)
print("Importe de M.O.D", mmm1)
print(separador)

print("producto C")
print("unidades a producir: ", restavel)
print("horas requeridas por unidad: ", horas_mano_de_obra1)
nnn2=(restavel * horas_mano_de_obra1)
print("total de horas requeridas", nnn2)
cua_1=(int(input("cuota por hora")))
mmm2=(nnn2 * cua_1)
print("Importe de M.O.D", mmm2)
print(separador)

print("totales primer semestre")
qqq=(nnn + nnn1 + nnn2)
print("total de horas requerida por semestre: ", qqq)
www=(mmm + mmm1 + mmm2)
print("total de M.O.D por semestre: ", www)

print(separador)
print("segundo semestre")

print("producto A")
print("unidades a producir: ", restav1)
print("horas requeridas por unidad: ", horas_mano_de_obra)
nnn4=(restav1 * horas_mano_de_obra)
print("total de horas requeridas" , nnn4)
cua_04=(int(input("cuota por hora")))
mmm4=(nnn4 * cua_04)
print("Importe de M.O.D", mmm4)
print(separador)

print("producto B")
print("unidades a producir: ", restav11)
print("horas requeridas por unidad: ", horas_mano_de_obra0)
nnn15=(restav11 * horas_mano_de_obra0)
print("total de horas requeridas", nnn15)
cua_5=(int(input("cuota por hora")))
mmm15=(nnn15 * cua_5)
print("Importe de M.O.D", mmm15)
print(separador)

print("producto C")
print("unidades a producir: ", restav111)
print("horas requeridas por unidad: ", horas_mano_de_obra1)
nnn26=(restav111 * horas_mano_de_obra1)
print("total de horas requeridas", nnn26)
cua_16=(int(input("cuota por hora")))
mmm26=(nnn26 * cua_16)
print("Importe de M.O.D", mmm26)
print(separador)

print("totales  por primer semestre")
qqq1=(nnn4 + nnn15 + nnn26)
print("total de horas requerida por semestre: ", qqq1)
www1=(mmm4 + mmm15 + mmm26)
print("total de M.O.D por semestre: ", www1)

print(separador)
print("totales de año")
print("producto 1")
print("unidades a producir: ", lokin)
print("horas requeridas por unidad", horas_mano_de_obra)
eee=(nnn + nnn4)
print("total de horas requeridas: ", eee)
pop=(mmm + mmm4)
print("importe de M.O.D: ", pop)
print(separador)
print("producto 2")
print("unidades a producir: ", lokin1)
print("horas requeridas por unidad", horas_mano_de_obra0)
eee1=(nnn1 + nnn15)
print("total de horas requeridas: ", eee1)
pop1=(mmm1 + mmm15)
print("importe de M.O.D: ", pop1)
print(separador)
print("producto 3")
print("unidades a producir: ", lokin10)
print("horas requeridas por unidad", horas_mano_de_obra1)
eee2=(nnn2 + nnn26)
print("total de horas requeridas: ", eee2)
pop2=(mmm2 + +mmm26)
print("importe de M.O.D: ", pop2)
print(separador)
fff=(qqq + qqq1)
print("total de hora por año: ", fff)
rrr=(www + www1)
print("total de M.O.D por año: ", rrr)
print(separador)

print("8-.presupuesto de gastos indirectos de fabricacion")
print("primer semestre")
ttu=(depress/2)
print("depreciacion: ", ttu)
ttu1=(segutos/2)
print("seguros: ",ttu1)
print("mantenimiento: ",manteni)
print("energeticos: ", ener)
ttu0=(vanito/2)
print("varios: ", ttu0)

ttt2=(ttu + ttu1 + manteni + ener + ttu0)
print("total G.I.F por semestre: ", ttt2)
print(separador)
print("segundo semestre")
print("depreciacion: ", ttu)
print("seguros: ", ttu1)
print("mantenimiento: ",manteri)
print("energeticos: ",enery)
print("varios: ", ttu0)
ttt2u=(ttu + ttu1 + manteri + enery + ttu0)
print("total G.I.F por semestre: ", ttt2u)

print("total por año")
zzz=(ttu + ttu)
print("depreciacion: ", zzz)
xxx=(ttu1 + ttu1)
print("seguros: ", xxx)
ccc=(manteni + manteri)
print("mantenimiento: ", ccc)
vvv=(ener + enery)
print("energeticos: ", vvv)
hg=(ttu0 + ttu0)
print("varios: ", hg)
poiuy=(zzz + xxx + ccc + vvv + hg)
print("total G.I.F por año: ", poiuy)

print(separador)
print("coeficiente para determinar el costo por hora de gastos indirectos de fabricacion")
print("total de G.I.F: ", poiuy)
print("total horas M.O.D anual: ", rrr)
vb=(poiuy / rrr)
print("total de gastos de operacion: ", vb)

print(separador)

print("9-.propuesto de gastos de operacion")
entre=(depre/2)
entre0=(ss/2)
muy=(prim_re* 0.01)
entre1=(inteli/2)
glop=(entre + entre0 + muy + entre1 + vari)

print("primer semestre")
print("depreciacion: ", entre)
print("sueldos y comisiones: ", entre0)
print("comisiones: ",muy)
print("varios: ",vari)
print("intereses del prestamo: ", entre1)
print("total de gastos de operacion: ", glop)
print(separador)

e1ntre=(depre/2)
e1ntre0=(ss/2)
m1uy=(seg_tre* 0.01)
e1ntre1=(inteli/2)
g1lop1=(e1ntre + e1ntre0 + m1uy + e1ntre + varen)

print("segundo semestre  ")
print("depreciacion: ", e1ntre)
print("sueldos y comisiones: ", e1ntre0)
print("comisiones: ", m1uy)
print("varios: ", varen)
print("intereses del prestamo: ", e1ntre1)
print("total de gastos de operacion: ", g1lop1)
print(separador)
print("total año")
zape=(entre + e1ntre)
zape0=(entre0 + e1ntre0)
zape1=(muy + m1uy)
zape2=(vari + varen)
zape3=(entre1 + e1ntre1)
zape5=(zape + zape1 + zape2 + zape3 )
print("depreciacion: ", zape)
print("sueldos y comisiones: ", zape0)
print("comisiones: ", zape1)
print("varios: ", zape2)
print("intereses del prestamo: " , zape3)
print("total de gastos de operacion: ", zape5)

print(separador)
print("10-. determinacion de costo de productos terminados")
print("producto 1 ")
print("costos")
print("material a:  $", mate12)
print("material b:  $", matea12)
print("material c:  $", mates12)
print("mano de obra:  ", cua_0)
print("gastos indirectos de fabricacion: ", zape5 )
print(separador)
print("producto 2 ")
print("costos")
print("material a:  $", mate12)
print("material b:  $", matea12)
print("material c:  $", mates12)
print("mano de obra:  ", cua_0)
print("gastos indirectos de fabricacion: ", zape5 )
print(separador)
print("producto 3 ")
print("costos")
print("material a:  $", mate12)
print("material b:  $", matea12)
print("material c:  $", mates12)
print("mano de obra:  ", cua_0)
print("gastos indirectos de fabricacion: ", zape5 )
print(separador)
#########################################################
print("producto 1 ")
print("cantidad")
print("material a: ", materia_prima_1)
print("material b: ", materia_prima_2)
print("material c: ", materia_prima_3)
print("mano de obra: ", horas_mano_de_obra)
print("gastos indirectos de fabricacion: ", horas_mano_de_obra)
print(separador)
print("producto 2 ")
print("cantidad")
print("material a: ", materia_prima_10)
print("material b: ", materia_prima_20)
print("material c: ", materia_prima_30)
print("mano de obra: ", horas_mano_de_obra0)
print("gastos indirectos de fabricacion: ", horas_mano_de_obra0)
print(separador)
print("producto 3 ")
print("cantidad")
print("material a: ", materia_prima_11)
print("material b: ", materia_prima_21)
print("material c: ", materia_prima_31)
print("mano de obra: ", horas_mano_de_obra1)
print("gastos indirectos de fabricacion: ", horas_mano_de_obra1)
print(separador)

###################################################
qqqq=(mate12 * materia_prima_1)
wwww=(matea12 * materia_prima_2)
eeee=(mates12 * materia_prima_3)
rrrr=(cua_0 * horas_mano_de_obra)
TTTT=(zape5 * horas_mano_de_obra)
yyyyy=(qqqq + wwww + eeee + rrrr + TTTT)
print("producto 1 ")
print("costo unitario")
print("material a: ", qqqq)
print("material b: ", wwww)
print("material c: ", eeee)
print("mano de obra: ", rrrr)
print("gastos indirectos de fabricacion: ", TTTT)
print("costo unitario: ", yyyyy)

qqqq1=(mate12 * materia_prima_10)
wwww1=(matea12 * materia_prima_20)
eeee1=(mates12 * materia_prima_30)
rrrr1=(cua_0 * horas_mano_de_obra0)
TTTT1=(zape5 * horas_mano_de_obra0)
yyyyy1=(qqqq1 + wwww1 + eeee1 + rrrr1 + TTTT1)
print("producto 2 ")
print("costo unitario")
print("material a: ", qqqq1)
print("material b: ", wwww1)
print("material c: ", eeee1)
print("mano de obra: ", rrrr1)
print("gastos indirectos de fabricacion: ", TTTT1)
print("costo unitario: ", yyyyy1)

qqqq2=(mate12 * materia_prima_11)
wwww2=(matea12 * materia_prima_21)
eeee2=(mates12 * materia_prima_31)
rrrr2=(cua_0 * horas_mano_de_obra1)
TTTT2=(zape5 * horas_mano_de_obra1)
yyyyy2=(qqqq2 + wwww2 + eeee2 + rrrr2 + TTTT2)
print("producto 3 ")
print("costo unitario")
print("material a: ", qqqq2)
print("material b: ", wwww2)
print("material c: ", eeee2)
print("mano de obra: ", rrrr2)
print("gastos indirectos de fabricacion: ", TTTT2)
print("costo unitario: ", yyyyy2)
print(separador)

print("11-.valuacion de inventarios finales")
print("inventario final de materiales")
print("unidades")
print("material a: ",mate )
print("material b: ", matea)
print("material c: " , mates)
print(separador)
print("costo unitario")
print("material a: ", mate12)
print("material b: ", matea12)
print("material c: ", mates12)
print(separador)
poi=(mate * mate12)
poiuyt=(matea * matea12)
qwrt=(mates * mates12)
vcd=(poi + poiuyt + qwrt)
print("costo total")
print("material a: ", poi)
print("material b: ", poiuyt)
print("material c: ", qwrt)
print("inventario final de materiales: ", vcd)
print(separador)

print("inventario final de producto terminado")
print("unidades")
print("material a: ",proc )
print("material b: ", procc)
print("material c: " , proccc)
print("costo unitario")
print("material a: ", yyyyy)
print("material b: ", yyyyy1)
print("material c: ", yyyyy2)
poi3=(proc * yyyyy)
poiuyt3=(procc * yyyyy1)
qwrt3=(proccc * yyyyy2)
vcd3=(poi3 + poiuyt3 + qwrt3)
print("costo total")
print("material a: ", poi3)
print("material b: ", poiuyt3)
print("material c: ", qwrt3)
print("inventario final de materiales: ", vcd3)

print(separador)

print("estado de costo de produccion y ventas")
print("saldo inicial de maeriales: $", int_mst)
print("(+)compras de materiales: ", opi)
rew=(int_mst + opi)
print("(=)material disponible: ", rew)
print("(-)inventario final de materiales: ", vcd)
resta=(rew - vcd)
print("(=)materiales utilizados: ", resta)
print("(+)mano de obra directa: ", rrr)
print("(+)mano de obra directa: ", poiuy)
suma=(resta + rrr + poiuy)
print("(=)gastos de fabricacion indirectos: ", suma)
print("(+)inventario inicial de productos terminados: ", int_tert)
suma1=(suma + int_tert)
print("(=)total de productos disponibles: ", suma1)
print("(-)inventario final de productos terminados: ", vcd3)
resta1=(suma1 - vcd3)
print("(=)costo de ventas: $", resta1)
print(separador)

print("estado de resultados")
print("ventas: $", sum4)
print("(-)costo de ventas: ", resta1)
ytry=(sum4 - resta1)
print("(=)utilidad bruta: ",ytry)
print("(-)gastos de operacion: ", zape5)
yrty=(ytry - zape5)
print("(=)utilidad de operacion: ",yrty)
asd=(yrty * 0.3)
print("(-)ISR: ", asd)
asd1=(yrty * 0.1)
print("(-)PTU: ",asd1)
zxcb=(yrty - asd - asd1)
print("(=)utilidad neta:", zxcb)

print(separador)

print("estado de flujo por efetivo")
print("saldo inicial de efectivo: $", efec)
print("entradas:")
print("cobranza: ", uwu)
print("cobranza 2: ", cli)
rjneg=(uwu + cli)
thr=(efec + rjneg)
print("total de entradas: ",rjneg)
print("efectivo disponible: ", thr)
print("salidas")
print("proveedores: ", bbb)
print("proveedores 2: ", provee)
print("pago manos de obra directa: ", rrr)
fjfju=(rrr - zzz)
print("pago gastos indirectos de fabricacion: ",fjfju)
svsv=(zape5 - zape)
print("pago de gastos de operacion: ", svsv)
maquina=(int(input("compra de activo fijo (maquinaria): ")))
print("pago ISR: ", isr)
et=(bbb + provee + rrr+ fjfju + svsv + maquina)
print("total de salidas", et)
bbbb=(thr - et)
print("flujo de efectivo actual: $", bbbb)
print(separador)

print("balance general")
print("activo circulante")

print("efectivo: ", bbbb)
print("clientes: ", tern8m)
print("deudores diversos: ", deudo)
print("funcionarios y empleados: ", fun)
print("inventario de materiales: ", vcd)
print("inventario de producto terminado: ", vcd3)
oooo=(bbbb + tern8m + deudo + fun + vcd + vcd3)
print("total de activos circulantes: ", oooo)

print("activo no circulante")
print("terreno: ", terr)
pla=(plant + maquina)
print("planta y equipo: ", pla)
lpa=(decer - zzz -zape)
print("depreciacion acomulada: ", lpa)
oooo1=(terr + pla + lpa )
print("total de activos no circulantes: ", oooo1)
suman=(oooo +oooo1)
print("activo total: ", suman)

print("pasivo a corto plazo")
print("proveedores: ", ttt)
print("documentos a pagar: ", docum)
print("ISR por pagar: ", asd)
print("PTU por pagar", asd1)
vbvb=(ttt + docum + asd + asd1)
print("total de pasivo corto plazo: ", vbvb)


print("pasivo largo plazo")
print("prestamos bancarios: ", presr)
print("total de pasivo largo plazo: ",presr)

suma2=(vbvb + presr)
print("pasivo total", suma2)

print("capital contable")
print("capital contribuido: ", capo)
print("capital ganado: ", cap_gan)
print("utilidad de ejercicio: ", zxcb)
suma4=(capo + cap_gan + zxcb)
print("total de capital contable: ", suma4)
suma45=(suma2 + suma4)
print("suma de pasivo y capital: ", suma45)